# Generated by Django 3.2.6 on 2021-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала активности')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания активности')),
                ('activity_type', models.CharField(choices=[('bike', 'Велосипед'), ('walking', 'Ходьба'), ('running', 'Бег')], max_length=9)),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние')),
                ('calories', models.PositiveIntegerField(verbose_name='Количество калорий')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
    ]
